postgresqldata:
  build: images/data
  volumes:
    - ./data/dumps:/media/dbdump:rw

postgresql:
  build: images/postgres
  restart: always
  env_file:
    - ./images/postgres/postgres.env
  volumes:
   - ./data/pg:/var/lib/postgresql/data
  expose:
   - "5432"

musicbrainz:
  build: images/musicbrainz
  ports:
   - "5000:5000"
  volumes_from:
   - postgresqldata
  restart: always
  environment:
   - MUSICBRAINZ_USE_PROXY=1
  expose:
   - "5000"
  links:
   - postgresql:db
   - search:search

indexer:
  build: images/indexer
  links:
   - postgresql:db
  volumes:
   - ./data/misc:/home/search/data

search:
  build: images/search
  expose:
   - "8080"
  volumes:
   - ./data/misc:/home/search/data
