version: "2"

services:

  postgresql:
    build: images/postgres
    container_name: postgresql
    restart: always
    env_file:
      - ./images/postgres/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      default:
        aliases:
          - db

  manager:
    build: images/manager
    container_name: manager
    ports:
      - "5000:5000"
    volumes:
      - dumps:/media/dbdump:rw
    restart: always
    env_file:
      - ./images/postgres/postgres.env
    environment:
      - MUSICBRAINZ_USE_PROXY=1
    expose:
      - "5000"
    links:
      - postgresql:db
      - search:search

  indexer:
    build: images/indexer
    container_name: indexer
    links:
      - postgresql:db
    volumes:
      - search:/home/search/data

  search:
    build: images/search
    container_name: search
    expose:
      - "8080"
    volumes:
      - search:/home/search/data

volumes:
  dumps:
    external: false
  postgres:
    external: false
  search:
    external: false
